FROM jboss/wildfly:14.0.1.Final
ADD blz-ds.xml /opt/jboss/wildfly/standalone/deployments/
ADD sep-ds.xml /opt/jboss/wildfly/standalone/deployments/
ADD postgresql-42.2.5.jar /opt/jboss/wildfly/standalone/deployments/
ADD sep-gruppe-5.war /opt/jboss/wildfly/standalone/deployments/
